[package]
name = "glassy_pdm_client"
version = "0.4.0"
description = "An innovative PDM solution"
authors = ["Joshua Tenorio"]
license = "GPL"
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
tauri = { version = "1.4", features = [ "shell-all", "path-all", "dialog-all", "fs-all"] }
tauri-plugin-store = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
merkle_hash = "3.5"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
reqwest = { version = "0.11.20", features = ["multipart", "blocking", "json"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
